### ISSUE TITLE
Compiling issues on MacOS 10.14.1

### ISSUE THREAD

**Issue by rcampbel3** [stefanhaustein/TerminalImageViewer#36]
I'm unable to compile tiv on macos 10.14.1 where it used to work in the not too distant past.

when I try to compile latest source from github on macos, I get:

ross@Rosss-MacBook-Air:~/project/TerminalImageViewer/src/main/cpp$ make
g++ -std=c++17  -Wall -fpermissive -fexceptions -O2 -c tiv.cpp -o tiv.o
tiv.cpp:8:10: fatal error: 'experimental/filesystem' file not found
#include <experimental/filesystem>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [tiv.o] Error 1

**Comment by mmartinez8020** [comment]
Getting the same error on 10.14.1

**Comment by stefanhaustein** [comment]
I'll have a look as soon as I have updated my machine O:)

**Comment by boretom** [comment]
Hi, not sure you still got the problem. I ran into the same and solved it by install gcc using brew and modify the src/main/cpp/Makefile to change CXX=g++ to CXX=g++-8. And compiling using the following (making it use homebrew gcc) in src/main/cpp:

PATH=/usr/local//Cellar/gcc/8.3.0/bin:$PATH CPPFLAGS="-I/usr/local//Cellar/gcc/8.3.0/include/c++/8.3.0/ -I/usr/local//Cellar/gcc/8.3.0/include/ -I/usr/local//Cellar/gcc/8.3.0/include/c++/8.3.0/x86_64-apple-darwin17.7.0/ -I/usr/local/Cellar/cimg/2.3.6/include/" LDFLAGS=-I/usr/local//Cellar/gcc/8.3.0/lib make

**Comment by stefanhaustein** [comment]
@boretom -- could your makefile improvement have fixed this? If so I'd just close this....

**Comment by boretom** [comment]
Hey @stefanhaustein,

Nope, not really but it has nothing to do with tiv, that's not a bug of tiv.

`<experimental/filesystem>` is still not part of Xcode that's why one has to install gcc using homebrew and refer to it to compile.

**Comment by stefanhaustein** [comment]
Ok. I'll add a corresponding hint to the README and close this as WAI then.

**Comment by mrob27** [comment]
I found a much simpler solution: just do without filesystem entirely.

It only requires removing the test of "`std::experimental::filesystem::is_directory`" and the following `for` loop, leaving just "`file_names.push_back(arg);`"

This means you can no longer view a directory as thumbnails with "**tiv dirname**", but so what? I can type "**tiv dirname/***" and get the same thing.

If you want to compile with GCC 4.8.x you'll also have to change the two array initialisers in `struct CharData` from `{0}` to `{{0}}`.

**Comment by saagarjha** [comment]
Recent versions of Xcode now ship with `<filesystem>`.

**Comment by boretom** [comment]
@saagarjha that is not correct. `<filesystem>` is included starting with the **latest macOS** 10.15 Catalina `<filesystem>`. It doesn't depend on Xcode, I have Xcode 11.3.1 installed on macOS 10.14.6 and it doesn't work. It even throws errors saying:

    `tiv.cpp:502:42: error: 'is_directory' is unavailable: introduced in macOS 10.15`

**Comment by saagarjha** [comment]
The filesystem libraries shipped with macOS Catalina, but the headers are included in Xcode if you compile with the right (10.15) SDK. You should be able to find `<filesystem>` at Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/filesystem.

**Comment by boretom** [comment]
@saagarjha I'd be interested in an example how to do that. It finds the headers just fine but then  tells me that it was `marked unavailable`

```gcc
tiv.cpp:503:24: error: 'directory_iterator' is unavailable: introduced in macOS 10.15
         for (auto & p : std::experimental::filesystem::directory_iterator(arg)) {
                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:2433:3: note: 'directory_iterator' has been explicitly
      marked unavailable here
```

**Comment by saagarjha** [comment]
Uh, does adding `-mmacos-version-min=10.15` to your build flags help?

**Comment by boretom** [comment]
@saagarjha it helps only partially, it's not complaining about the headers anymore. But it can't find the methods while linking. Removing `-lstd++fs` didn't not help, add `-lstd++` instead neither.

**Comment by aaronliu0130** [comment]
Fixed as of #98 .
